services:
  - type: web
    name: preethi-nutrition-center
    env: node
    region: singapore
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: DEFAULT_ADMIN_EMAIL
        value: admin@preethinutrition.com
      - key: DEFAULT_ADMIN_PASSWORD
        sync: false
